---
# Source: kindling/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kindling-agent-svc-account
  namespace: kindling
  labels:
    helm.sh/chart: kindling-0.1.0
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
---
# Source: kindling/templates/configmaps.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kindling-agent-config
  namespace: kindling
data:
  kindling-collector-config.yml: |
    controller:
      http:
        enable: true
        port: :9503
      modules: ["profile"]
  
    receivers:
      cgoreceiver:
        subscribe:
          - name: syscall_exit-writev
            category: net
          - name: syscall_exit-readv
            category: net
          - name: syscall_exit-write
            category: net
          - name: syscall_exit-read
            category: net
          - name: syscall_exit-sendto
            category: net
          - name: syscall_exit-recvfrom
            category: net
          - name: syscall_exit-sendmsg
            category: net
          - name: syscall_exit-recvmsg
            category: net
          - name: syscall_exit-sendmmsg
            category: net
          - name: syscall_exit-recvmmsg
            category: net
          - name: kprobe-tcp_close
          - name: kprobe-tcp_rcv_established
          - name: kprobe-tcp_drop
          - name: kprobe-tcp_retransmit_skb
          - name: syscall_exit-connect
          - name: kretprobe-tcp_connect
          - name: kprobe-tcp_set_state
          - name: tracepoint-procexit
    analyzers:
      cpuanalyzer:
        # sampling_interval is the sampling interval for the same url. The unit is second.
        sampling_interval: 5
        # segment_size defines how many segments(seconds) can be cached to wait for sending.
        # The elder segments will be overwritten by the newer ones, so don't set it too low.
        segment_size: 40
        # edge_events_window_size is the size of the duration window that seats the edge events.
        # The unit is second. The greater it is, the more data will be stored.
        edge_events_window_size: 2
      tcpconnectanalyzer:
        channel_size: 10000
        wait_event_second: 10
        # Whether add pid and command info in tcp-connect-metrics's labels
        need_process_info: false
      tcpmetricanalyzer:
      networkanalyzer:
        connect_timeout: 100
        # How many seconds to wait until we consider a request as complete.
        fd_reuse_timeout: 2
        # How many seconds to wait until we consider a request as no response.
        no_response_threshold: 120
        # How many milliseconds to wait until we consider a request-response as slow.
        response_slow_threshold: 500
        # Whether enable conntrack module to find pod's ip when calling service
        enable_conntrack: true
        conntrack_max_state_size: 131072
        conntrack_rate_limit: 500
        proc_root: /proc
        # The protocol parsers which is enabled
        # When dissectors are enabled, agent will analyze the payload and enrich metric/trace with its content.
        protocol_parser: [ http, mysql, dns, redis, kafka, rocketmq ]
        # Which URL clustering method should be used to shorten the URL of HTTP request.
        # This is useful for decrease the cardinality of URLs.
        # Valid values: ["noparam", "alphabet", "blank"]
        # - noparam: Only trim the trailing parameters behind the character '?'
        # - alphabet: Trim the trailing parameters and Convert the segments
        #             containing non-alphabetical characters to star(*)
        # - blank: Turn endpoints to empty. This is used to reduce the cardinality as much as possible.
        url_clustering_method: alphabet
        # If the destination port of data is one of the followings, the protocol of such network request
        # is set to the corresponding one. Note the program will try to identify the protocol automatically
        # for the ports that are not in the lists, in which case the cpu usage will be increased much inevitably.
        protocol_config:
          - key: "http"
            ports: [ 80 ]
            # payload_length indicates the maximum size that payload can be fetched for target protocol
            # The trace data sent may contain such payload, so the higher this value, the larger network traffic.
            payload_length: 200
            slow_threshold: 500
          # The Dubbo parser is experimental now, so it is disabled by default. You could enable it by adding it
          # to the "protocol_parser" array.
          - key: "dubbo"
            payload_length: 200
          - key: "mysql"
            ports: [ 3306 ]
            slow_threshold: 100
            disable_discern: false
          - key: "kafka"
            ports: [ 9092 ]
            slow_threshold: 100
          - key: "redis"
            ports: [ 6379 ]
            slow_threshold: 100
          - key: "dns"
            ports: [ 53 ]
            slow_threshold: 100
          - key: "rocketmq"
            ports: [ 9876, 10911 ]
            slow_threshold: 500
  
    processors:
      k8smetadataprocessor:
        # Set "enable" false if you want to run the agent in the non-Kubernetes environment.
        # Otherwise, the agent will panic if it can't connect to the API-server.
        enable: true
        kube_auth_type: serviceAccount
        kube_config_dir: /root/.kube/config
        # GraceDeletePeriod controls the delay interval after receiving delete event.
        # The unit is seconds, and the default value is 60 seconds.
        # Should not be lower than 30 seconds.
        grace_delete_period: 60
        # enable_fetch_replicaset controls whether to fetch ReplicaSet information.
        # The default value is false. It should be enabled if the ReplicaSet
        # is used to control pods in the third-party CRD except for Deployment.
        enable_fetch_replicaset: false
      aggregateprocessor:
        # Aggregation duration window size. The unit is second.
        ticker_interval: 5
        aggregate_kind_map:
          request_total_time:
            - kind: sum
            - kind: avg
              output_name: request_total_time_avg
            - kind: count
              output_name: request_count
          request_io:
            - kind: sum
          response_io:
            - kind: sum
          kindling_tcp_srtt_microseconds:
            - kind: last
          kindling_tcp_retransmit_total:
            - kind: sum
          kindling_tcp_packet_loss_total:
            - kind: sum
          kindling_tcp_connect_total:
            - kind: sum
          kindling_tcp_connect_duration_nanoseconds_total:
            - kind: sum
        sampling_rate:
          normal_data: 0
          slow_data: 100
          error_data: 100
  
    exporters:
      cameraexporter:
        # Options: ["file", "elasticsearch"]
        storage: file
        # Effective when storage is "file"
        file_config:
          storage_path: /tmp/kindling
          # Max file count for each process
          max_file_count_each_process: 50
        # Effective when storage is "elasticsearch"
        es_config:
          es_host: http://10.10.10.10:9200
          index_suffix: dev
      otelexporter:
        adapter_config:
          need_trace_as_metric: true
          need_pod_detail: true
          store_external_src_ip: true
          # When using otlp-grpc / stdout exporter , this option supports to
          # send trace data in the format of ResourceSpan
          need_trace_as_span: false
        metric_aggregation_map:
          kindling_entity_request_total: counter
          kindling_entity_request_duration_nanoseconds_total: counter
          kindling_entity_request_send_bytes_total: counter
          kindling_entity_request_receive_bytes_total: counter
          kindling_topology_request_total: counter
          kindling_topology_request_duration_nanoseconds_total: counter
          kindling_topology_request_request_bytes_total: counter
          kindling_topology_request_response_bytes_total: counter
          kindling_trace_request_duration_nanoseconds: gauge
          kindling_tcp_srtt_microseconds: gauge
          kindling_tcp_retransmit_total: counter
          kindling_tcp_packet_loss_total: counter
          kindling_tcp_connect_total: counter
          kindling_tcp_connect_duration_nanoseconds_total: counter
        # Export data in the following ways: ["prometheus", "otlp", "stdout"]
        # Note: configure the corresponding section to make everything ok
        export_kind: prometheus
        # Add labels to all metrics in the format of [key: value]
        custom_labels:
        prometheus:
          port: :9500
        otlp:
          collect_period: 15s
          # Note: DO NOT add the prefix "http://"
          endpoint: 10.10.10.10:8080
        stdout:
          collect_period: 15s
  
    observability:
      logger:
        console_level: info # debug,info,warn,error,none
        file_level: info
        # debug_selector is used to filter debug message from different components
        # 1. This filter will not take effect when there is no element in the debug_selector list
        # 2. If the list is not empty, only the components contained in this list will print debug message
        # 3. The name of each component is defined above, such as `receiver.cgoreceiver`, `exporter.otelexporter`, only the second part of the config name needed
        # e.g debug_selector: ["cgoreceiver","otelexporter"]
        debug_selector: []
        file_rotation:
          filename: agent.log
          maxsize: 512 #MB
          maxage: 30 #day
          maxbackups: 5
          localtime: true
          compress: false
      opentelemetry:
        # Export data in the following ways: ["prometheus", "otlp", "stdout"]
        # Note: configure the corresponding section to make everything ok
        export_kind: stdout
        prometheus:
          port: :9501
          # Self-metrics for special purpose
          # "resource" for agent CPU and memory usage metricss
          # extra_metrics: ["resource"]
        otlp:
          collect_period: 15s
          # Note: DO NOT add the prefix "http://"
          endpoint: 10.10.10.10:8080
        stdout:
          collect_period: 15s
---
# Source: kindling/templates/configmaps.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kindling-camera-front-config
data:
  settings.js: |
    const setting = {
        apmServerConfig: {
            host: 'kindling-agent-svc',
            port: '2234',
        },
        profileConfig: {
            host: 'kindling-agent-svc',
            port: '9503',
        },
        traceFilePath: '/tmp/kindling',
        port: 9504-svc,
    };
    module.exports = setting;
---
# Source: kindling/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kindling-agent-role
  namespace: kindling
  labels:
    helm.sh/chart: kindling-0.1.0
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - replicationcontrollers
  - services
  - endpoints
  - events
  - limitranges
  - namespaces
  - nodes
  - resourcequotas
  - persistentvolumes
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - daemonsets
  - deployments
  - ingresses
  - replicasets
  verbs:
  - get
  - list
  - watch
---
# Source: kindling/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  managedFields:
  - apiVersion: rbac.authorization.k8s.io/v1
    fieldsType: FieldsV1
  name: kindling-agent-role-binding
  namespace: kindling
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kindling-agent
subjects:
- kind: ServiceAccount
  name: kindling-agent
  namespace: kindling
---
# Source: kindling/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kindling-agent-svc
  labels:
    helm.sh/chart: kindling-0.1.0
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - name: "metrics"
      port: 9500
      targetPort: 9500
      protocol: TCP
    - name: "profile"
      port: 9503
      targetPort: 9503
      protocol: TCP
    - name: "apm"
      port: 2234
      targetPort: 2234
      protocol: TCP
  selector:
      app.kubernetes.io/name: kindling-agent
---
# Source: kindling/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kindling-camera-front-svc
  labels:
    helm.sh/chart: kindling-0.1.0
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 9504
      targetPort: 9504
      protocol: TCP
  selector:
    app.kubernetes.io/name: kindling-camera-front
---
# Source: kindling/templates/daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kindling-agent
  namespace: kindling
  labels:
    helm.sh/chart: kindling-0.1.0
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kindling-agent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kindling-agent
    spec:
      imagePullSecrets:
        - name: registrypullsecret
      serviceAccountName: kindling-agent-svc-account
      containers:
        - name: kindling-agent
          securityContext:
            privileged: true
          image: "registry.cn-hangzhou.aliyuncs.com/lenshood/kindling-agent:latest"
          imagePullPolicy: Always
          ports:
            - name: "metrics"
              containerPort: 9500
              protocol: TCP
            - name: "profile"
              containerPort: 9503
              protocol: TCP
            - name: "apm"
              containerPort: 2234
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - cat
                - /opt/kernel-support
          resources:
            limits:
              memory: 1500Mi
            requests:
              memory: 300Mi
          env:
            - name: HOST_PROC
              value: /host/proc
            - name: PL_HOST_PATH
              value: /host
            - name: SYSDIG_HOST_ROOT
              value: /host
            - name: SNAPLEN
              value: "1000"
            - name: GOGC
              value: "200"
            - name: switch_agg_num
              value: "2"
            - name: MY_NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - mountPath: /app/config
              name: kindling-agent-config
            - mountPath: /sys
              name: sys-vol
            - mountPath: /etc/modprobe.d
              name: modprobe-d
              readOnly: true
            - mountPath: /host/dev
              name: dev-vol
            - mountPath: /host/proc
              name: proc-vol
              readOnly: true
            - mountPath: /host/etc
              name: etc-vol
              readOnly: true
            - mountPath: /host/boot
              name: boot-vol
              readOnly: true
            - mountPath: /host/lib/modules
              name: modules-vol
              readOnly: true
            - mountPath: /host/usr
              name: usr-vol
              readOnly: true
            - mountPath: /host/run
              name: run-vol
            - mountPath: /host/var/run
              name: varrun-vol
            - mountPath: /dev/shm
              name: dshm
            - name: shared-data
              mountPath: /tmp/kindling
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      hostPID: true
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 420
            name: kindling-agent-config
          name: kindling-agent-config
        - hostPath:
            path: /etc/modprobe.d
          name: modprobe-d
        - emptyDir:
            medium: Memory
          name: dshm
        - hostPath:
            path: /dev
          name: dev-vol
        - hostPath:
            path: /proc
          name: proc-vol
        - hostPath:
            path: /etc
          name: etc-vol
        - hostPath:
            path: /boot
          name: boot-vol
        - hostPath:
            path: /lib/modules
          name: modules-vol
        - hostPath:
            path: /usr
          name: usr-vol
        - hostPath:
            path: /run
          name: run-vol
        - hostPath:
            path: /var/run
          name: varrun-vol
        - hostPath:
            path: /sys
          name: sys-vol
        - name: shared-data
          hostPath:
            path: /tmp/kindling/data
            type: DirectoryOrCreate
---
# Source: kindling/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kindling-camera-front
  namespace: kindling
  labels:
    helm.sh/chart: kindling-0.1.0
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kindling-camera-front
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kindling-camera-front
    spec:
      containers:
        - name: kindling-camera-front
          image: "kindlingproject/kindling-camera-front:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 9504
              protocol: TCP
          resources:
            limits:
              memory: 300Mi
            requests:
              memory: 30Mi
          volumeMounts:
          - mountPath: /app/camera-front/node/settings.js
            name: kindling-camera-front-config
            subPath: settings.js
          - name: shared-data
            mountPath: /tmp/kindling
      volumes:
        - configMap:
            name: kindling-camera-front-config
          name: kindling-camera-front-config
        - name: shared-data
          hostPath:
            path: /tmp/kindling/data
            type: DirectoryOrCreate
