apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.agent.name }}-svc-account
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kindling.labels" . | nindent 4 }}
  {{- with .Values.agent.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
